# Generated by Django 4.1.1 on 2023-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waitingapproval', 'Waitingaprroval'), ('active', 'Active'), ('deleted', 'Delected')], default='active', max_length=100),
        ),
    ]
