# Generated by Django 4.1.1 on 2023-03-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='marchant_id',
            new_name='payment_intent',
        ),
    ]
